[package]
authors = ["Kn0g"]
name = "CartesianTree"
version = "0.2.1"
edition = "2024"
description = "Build hierarchical Cartesian coordinate systems to easily transform poses."
homepage = "https://github.com/Kn0g/cartesian-tree"
readme = "README.md"
repository = "https://github.com/Kn0g/cartesian-tree"
license = "MIT"
include = ["/src"]
keywords = ["Cartesian", "coordinate-systems", "transform", "poses"]
categories = ["mathematics", "data-structures"]

[lints.clippy]
all = "warn"
style = "warn"
pedantic = "warn"
cargo = "warn"
nursery = "warn"
missing_panics_doc = "warn"
missing_errors_doc = "warn"
missing_safety_doc = "warn"
empty_line_after_outer_attr = "warn"
empty_line_after_doc_comments = "warn"

[dependencies]
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }
pyo3 = { version = "0.25.0", features = ["extension-module"] , optional = true}
thiserror = "2.0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
bindings = ["dep:pyo3"]

[lib]
name = "cartesian_tree"
crate-type = ["cdylib", "rlib"]

