# Type stubs for the Rust extension module `cartesian_tree._cartesian_tree`.
# Keep in sync with the pymethods in src/bindings/.

class Vector3:
    def __init__(self, x: float, y: float, z: float) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
    def to_tuple(self) -> tuple[float, float, float]: ...

class Rotation:
    @classmethod
    def from_quaternion(cls, x: float, y: float, z: float, w: float) -> Rotation: ...
    @classmethod
    def from_rpy(cls, roll: float, pitch: float, yaw: float) -> Rotation: ...
    @classmethod
    def identity(cls) -> Rotation: ...
    def as_quaternion(self) -> tuple[float, float, float, float]: ...
    def as_rpy(self) -> tuple[float, float, float]: ...

class Isometry:
    @classmethod
    def identity(cls) -> Isometry: ...
    @classmethod
    def from_translation(cls, translation: Vector3) -> Isometry: ...
    @classmethod
    def from_rotation(cls, rotation: Rotation) -> Isometry: ...
    @classmethod
    def from_parts(cls, translation: Vector3, rotation: Rotation) -> Isometry: ...
    def decompose(self) -> tuple[Vector3, Rotation]: ...
    def translation(self) -> Vector3: ...
    def rotation(self) -> Rotation: ...
    def inverse(self) -> Isometry: ...
    def __mul__(self, other: Isometry) -> Isometry: ...

class LazyTranslation: ...
class LazyRotation: ...

class Frame:
    def __init__(self, name: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def depth(self) -> int: ...
    @property
    def position(self) -> Vector3: ...
    @property
    def orientation(self) -> Rotation: ...
    def add_child(self, name: str, position: Vector3, orientation: Rotation) -> Frame: ...
    def remove_child(self, name: str) -> None: ...
    def calibrate_child(
        self,
        name: str,
        desired_position: Vector3,
        desired_orientation: Rotation,
        reference_pose: Pose,
    ) -> Frame: ...
    def add_pose(self, position: Vector3, orientation: Rotation) -> Pose: ...
    def transformation(self) -> tuple[Vector3, Rotation]: ...
    def set(self, position: Vector3, orientation: Rotation) -> None: ...
    def apply_in_parent_frame(self, isometry: Isometry) -> None: ...
    def apply_in_local_frame(self, isometry: Isometry) -> None: ...
    def to_json(self) -> str: ...
    def apply_config(self, json: str) -> None: ...
    def root(self) -> Frame: ...
    def parent(self) -> Frame | None: ...
    def children(self) -> list[Frame]: ...
    def __add__(self, other: LazyTranslation) -> Frame: ...
    def __sub__(self, other: LazyTranslation) -> Frame: ...
    def __mul__(self, other: LazyRotation) -> Frame: ...

class Pose:
    def frame(self) -> Frame | None: ...
    @property
    def position(self) -> Vector3: ...
    @property
    def orientation(self) -> Rotation: ...
    def transformation(self) -> tuple[Vector3, Rotation]: ...
    def set(self, position: Vector3, orientation: Rotation) -> None: ...
    def apply_in_parent_frame(self, isometry: Isometry) -> None: ...
    def apply_in_local_frame(self, isometry: Isometry) -> None: ...
    def in_frame(self, target_frame: Frame) -> Pose: ...
    def __add__(self, other: LazyTranslation) -> Pose: ...
    def __sub__(self, other: LazyTranslation) -> Pose: ...
    def __mul__(self, other: LazyRotation) -> Pose: ...

def x(value: float) -> LazyTranslation: ...
def y(value: float) -> LazyTranslation: ...
def z(value: float) -> LazyTranslation: ...
def rx(value: float) -> LazyRotation: ...
def ry(value: float) -> LazyRotation: ...
def rz(value: float) -> LazyRotation: ...
